LocadoraWebApp/Models/GrupoVeiculosViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace LocadoraWebApp.Models
{
        public class InserirGrupoVeiculosViewModel
        {
            [Required(ErrorMessage = "O nome é obrigatório")]
            [MinLength(3, ErrorMessage = "O nome deve conter ao menos 3 caracteres")]
            public string Nome { get; set; }
        }

        public class EditarGrupoVeiculosViewModel
        {
            public int Id { get; set; }

            [Required(ErrorMessage = "O nome é obrigatório")]
            [MinLength(3, ErrorMessage = "O nome deve conter ao menos 3 caracteres")]
            public string Nome { get; set; }
        }

        public class ListarGrupoVeiculosViewModel
        {
            public int Id { get; set; }
            public string Nome { get; set; }
        }

        public class DetalhesGrupoVeiculosViewModel
        {
            public int Id { get; set; }
            public string Nome { get; set; }
        }
    }

LocadoraWebApp/Controllers/GrupoVeiculosController.cs
using AutoMapper;
using Locadora.Aplicacao.ModuloAutenticacao;
using Locadora.Aplicacao.ModuloGrupoVeiculos;
using Locadora.Dominio.ModuloGrupoVeiculos;
using LocadoraWebApp.Controllers.Compartilhado;
using LocadoraWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace LocadoraWebApp.Controllers
{
    public class GrupoVeiculosController : WebControllerBase
    {
        private readonly ServicoGrupoVeiculos servico;
        private readonly IMapper mapper;

        public GrupoVeiculosController(ServicoAutenticacao servicoAutenticacao,ServicoGrupoVeiculos servico, IMapper mapper) : base(servicoAutenticacao)
        {
            this.servico = servico;
            this.mapper = mapper;
        }

        public IActionResult Listar()
        {
            var resultado = servico.SelecionarTodos();

            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult());

                return RedirectToAction("Index", "Home");
            }

            var grupos = resultado.Value;

            var listarGrupoVm = mapper.Map<IEnumerable<ListarGrupoVeiculosViewModel>>(grupos);

            return View(listarGrupoVm);
        }

        public IActionResult Inserir()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Inserir(InserirGrupoVeiculosViewModel inserirVm)
        {
            if (!ModelState.IsValid)
            {
                return View(inserirVm);
            }

            var grupo = mapper.Map<GrupoVeiculos>(inserirVm);

            var resultado = servico.Inserir(grupo);


            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult());
                return RedirectToAction(nameof ( Listar ));
            }

            ApresentarMensagemSucesso($"O registro ID [{grupo.Id}] foi inserido com sucesso!");
            return RedirectToAction("Listar");
        }

        public IActionResult Editar(int id)
        {
            var resultado = servico.SelecionarPorId(id);

            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult());

                return RedirectToAction(nameof ( Listar ));
            }

            var grupo = resultado.Value;

            var editarVm = mapper.Map<EditarGrupoVeiculosViewModel>(grupo);

            return View(editarVm);
        }

        [HttpPost]
        public IActionResult Editar(EditarGrupoVeiculosViewModel editarVm)
        {
            if (!ModelState.IsValid)
            {
                return View(editarVm);
            }

            var grupo = mapper.Map<GrupoVeiculos>(editarVm);

            var resultado = servico.Editar(grupo);


            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult());
                return RedirectToAction(nameof ( Editar ));
            }

            ApresentarMensagemSucesso($"O registro ID [{grupo.Id}] foi editado com sucesso!");
            return RedirectToAction(nameof(Editar));
        }

        public IActionResult Excluir(int id)
        {
            var resultado = servico.SelecionarPorId(id);

            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult()); 
                return RedirectToAction(nameof(Listar));
            }

            var grupo = resultado.Value;

            var detalhesVm = mapper.Map<DetalhesGrupoVeiculosViewModel>(grupo);

            return View(detalhesVm);
        }

        [HttpPost]
        public IActionResult Excluir(DetalhesGrupoVeiculosViewModel detalhesVm)
        {
            var resultado = servico.Excluir(detalhesVm.Id);

            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult());

                return RedirectToAction(nameof(Listar));
            }
            else
            {
                ApresentarMensagemSucesso($"O registro ID [{detalhesVm.Id}] foi excluído com sucesso!");
                return RedirectToAction(nameof(Listar));
            }
        }

        public IActionResult Detalhes(int id)
        {
            var resultado = servico.SelecionarPorId(id);

            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult());

                return RedirectToAction(nameof(Listar));
            }

            var grupo = resultado.Value;

            var detalhesVm = mapper.Map<DetalhesGrupoVeiculosViewModel>(grupo);

            return View(detalhesVm);
        }
    }
}

LocadoraWebApp/Views/GrupoVeiculos/Editarr.cshtml
@model LocadoraWebApp.Models.EditarGrupoVeiculosViewModel

@{
    ViewBag.Title = "Editar Grupo de Veículos";
}

<div class="col">
    <div class="row gap-3 my-3 my-xl-5">
        <form class="col-lg-6 d-grid gap-3 fs-5" asp-controller="GrupoVeiculos" asp-action="Editar">
            <div>
                <label class="control-label fw-semibold mb-1">Nome</label>
                <input class="form-control mb-1" asp-for="Nome"/>
                <span class="text-danger fs-6" asp-validation-for="Nome"></span>
            </div>

            <div class="d-grid gap-2 d-md-block mt-4">
                <button class="btn btn-primary px-5">
                    <i class="bi bi-floppy-fill me-1"></i>
                    Gravar
                </button>

                <a class="btn btn-outline-primary px-5" asp-controller="GrupoVeiculos" asp-controller="GrupoVeiculos" asp-action="Editar">
                    <i class="bi bi-arrow-return-left me-1"></i>
                    Voltar
                </a>
            </div>
        </form>
    </div>
</div>

LocadoraWebApp/Views/GrupoVeiculos/Excluirr.cshtml
@model LocadoraWebApp.Models.DetalhesGrupoVeiculosViewModel

@{
    ViewBag.Title = "Excluir";
}

<div class="col">
    <partial name="_Informacoes" model="Model"></partial>

    <form class="d-grid gap-2 d-md-block mt-5" asp-action="Excluir">
        <button class="btn btn-danger px-5">
            <i class="bi bi-trash-fill me-1"></i>
            Confirmar
        </button>

        <a class="btn btn-outline-primary px-5" asp-action="Listar">
            <i class="bi bi-arrow-return-left me-1"></i>
            Voltar
        </a>
    </form>
</div>

LocadoraWebApp/Views/GrupoVeiculos/Inserir.cshtml
@model LocadoraWebApp.Models.InserirGrupoVeiculosViewModel

@{
    ViewBag.Title = "Inserir Grupo de Veículos";
}

<div class="col">
    <div class="row gap-3 my-3 my-xl-5">
        <form class="col-lg-6 d-grid gap-3 fs-5" asp-controller="GrupoVeiculos" asp-action="Inserir">
            <div>
                <label class="control-label fw-semibold mb-1">Nome</label>
                <input class="form-control mb-1" asp-for="Nome"/>
                <span class="text-danger fs-6" asp-validation-for="Nome"></span>
            </div>

            <div class="d-grid gap-2 d-md-block mt-4">
                <button class="btn btn-primary px-5">
                    <i class="bi bi-floppy-fill me-1"></i>
                    Gravar
                </button>

                <a class="btn btn-outline-primary px-5" asp-controller="GrupoVeiculos" asp-action="Listar">
                    <i class="bi bi-arrow-return-left me-1"></i>
                    Voltar
                </a>
            </div>
        </form>
    </div>
</div>

LocadoraWebApp/Views/GrupoVeiculos/Listar.cshtml
@model IEnumerable<LocadoraWebApp.Models.ListarGrupoVeiculosViewModel>

@{
    ViewBag.Title = "Listagem de Grupos de Veículos";
}

<div class="col">

    <a class="btn btn-primary px-4 mt-3" asp-controller="GrupoVeiculos" asp-action="Inserir">
        <i class="bi bi-circle-add"></i>
        Inserir Novo Grupo de Veículos
    </a>

    <div class="row gap-2 my-3 my-xl-5">
        @foreach (var grupoVm in Model)
        {
            <div class="card col-lg-4 col-xl-3">
                <div class="card-header bg-transparent d-flex justify-content-between align-items-center">
                    <h5 class="p-0">@grupoVm.Id</h5>

                    <div class="text-end d-flex align-items-center gap-3">
                        <a title="Detalhes"
                           class="text-info-emphasis fs-5"
                           href="/GrupoVeiculos/Detalhes/@grupoVm.Id">
                            <i class="bi bi-search"></i>
                        </a>
                        <a title="Editar"
                           class="text-info-emphasis fs-5"
                           href="/GrupoVeiculos/Editar/@grupoVm.Id">
                            <i class="bi bi-pencil-fill"></i>
                        </a>
                        <a title="Excluir"
                           class="text-info-emphasis fs-5" href="/GrupoVeiculos/Excluir/@grupoVm.Id">
                            <i class="bi bi-trash-fill"></i>
                        </a>
                    </div>
                </div>

                <div class="card-body">
                    <h5 class="card-title">@grupoVm.Nome</h5>
                </div>
            </div>
        }
    </div>
</div>

LocadoraWebApp/Views/GrupoVeiculos/_Informacoes.cshtml
@model LocadoraWebApp.Models.DetalhesGrupoVeiculosViewModel

<div class="row gap-3 my-3 my-xl-5">
    <label class="fs-4"><strong>Grupo:</strong> @Model.Nome</label>

    <label class="fs-5"><strong>Id:</strong> [@Model.Id]</label>
</div>

LocadoraWebApp/Views/GrupoVeiculos/_Informacoess.cshtml
@model LocadoraWebApp.Models.DetalhesGrupoVeiculosViewModel

<div class="row gap-3 my-3 my-xl-5">
    <label class="fs-4"><strong>Grupo:</strong> @Model.Nome</label>

    <label class="fs-5"><strong>Id:</strong> [@Model.Id]</label>
</div>