LocadoraWebApp/Models/MensagemViewModel.cs
namespace LocadoraWebApp.Models;

    public class MensagemViewModel
    {
        public string Titulo { get; set; }
        public string Mensagem { get; set; }
    }

LocadoraWebApp/Controllers/AutenticacaoController.cs
using Locadora.Aplicacao.ModuloAutenticacao;
using Locadora.Dominio.ModuloAutenticacao;
using LocadoraWebApp.Controllers.Compartilhado;
using LocadoraWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace LocadoraWebApp.Controllers
{
    public class AutenticacaoController : WebControllerBase
    {
        private readonly ServicoAutenticacao servicoAutenticacao;

        public AutenticacaoController(ServicoAutenticacao servicoAutenticacao) : base(servicoAutenticacao)
        {
            this.servicoAutenticacao = servicoAutenticacao;
        }

        public IActionResult Registrar()
        {
            return View(new RegistrarViewModel()); // registrar view model
        }

        [HttpPost]
        public async Task<IActionResult> Registrar(RegistrarViewModel registrarVm) // registrar view model, registrarVm
        {
            if (!ModelState.IsValid)
                return View(registrarVm);

            var usuario = new Usuario()
            {
                UserName = registrarVm.Usuario,
                Email = registrarVm.Email
            };

            var senha = registrarVm.Senha!;

            var resultado = await servicoAutenticacao.Registrar(usuario, senha, TipoUsuarioEnum.Empresa);

            if (resultado.IsSuccess)
                return RedirectToAction("Index", "Home");
            
            foreach (var erro in resultado.Errors)
                ModelState.AddModelError(string.Empty, erro.Message);

            return View(registrarVm);
        }

        public IActionResult Login(string ? returnUrl = null)
        {
            ViewBag.ReturnUrl = returnUrl;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel loginVm, string ? returnUrl = null)
        {
            ViewBag.ReturnUrl = returnUrl;

            if (!ModelState.IsValid)
                return View(loginVm);

            var resultado = await servicoAutenticacao.Login(loginVm.Usuario!, loginVm.Senha!);

            if (resultado.IsSuccess)
                return LocalRedirect(returnUrl ?? "/");

            var msgErro = resultado.Errors.First().Message;
            
            ModelState.AddModelError(string.Empty, msgErro);

            return View(loginVm);
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await servicoAutenticacao.LogOut();

            return RedirectToAction(nameof ( Login ));
        }

        public IActionResult AcessoNegado()
        {
            return View();
        }
    }
}

LocadoraWebApp/Views/Shared/_Layout.cshtml
@using LocadoraWebApp.Models
@using Microsoft.AspNetCore.Mvc.TagHelpers
@{
    MensagemViewModel? mensagem = ViewBag.Mensagem ?? null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - Locadora De Veículos</title>
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
</head>
<body>
    <div class="container-fluid">
        <div class="row flex-nowrap">
            
            <nav class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 text-bg-light">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 min-vh-100">
                    <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-decoration-none text-dark">
                        <span class="fs-4 fw-bold d-none d-sm-inline">Locadora de Veículos</span>
                    </a>
                    
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                        @if (User.Identity is not null && User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a href="/" title="Inicio" class="nav-link align-middle px-0  text-decoration-none text-primary">
                                    <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Início</span>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a href="/GrupoVeiculos/Listar" title="Grupos de Veículos" class="nav-link align-middle px-0  text-decoration-none text-primary">
                                    <i class="fs-4 bi-collection-fill"></i> <span class="ms-1 d-none d-sm-inline">Grupos de Veículos</span>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a href="/Veiculos/Listar" title="Veículos" class="nav-link align-middle px-0  text-decoration-none text-primary">
                                    <i class="fs-4 bi-car-front-fill"></i> <span class="ms-1 d-none d-sm-inline">Veículos</span>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a href="/PlanoCobrancas/Listar" title="Planos de Cobrança" class="nav-link align-middle px-0  text-decoration-none text-primary">
                                    <i class="fs-4 bi-currency-exchange"></i> <span class="ms-1 d-none d-sm-inline">Planos de Cobrança</span>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a href="/Taxas/Listar" title="Taxas" class="nav-link align-middle px-0  text-decoration-none text-primary">
                                    <i class="fs-4 bi-tags-fill"></i> <span class="ms-1 d-none d-sm-inline">Taxas</span>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a href="/Combustiveis/Configurar" title="Configuração de Combustível" class="nav-link align-middle px-0  text-decoration-none text-primary">
                                    <i class="fs-4 bi-gear-fill"></i> <span class="ms-1 d-none d-sm-inline">Combustíveis</span>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a href="/Locacao/Listar" title="Locações" class="nav-link align-middle px-0  text-decoration-none text-primary">
                                    <i class="fs-4 bi-shop"></i> <span class="ms-1 d-none d-sm-inline">Locações</span>
                                </a>
                            </li>

                            @if (User.IsInRole("Empresa"))
                            {
                                <li class="nav-item">
                                    <a href="/Funcionario/Listar" title="Funcionários" class="nav-link align-middle px-0  text-decoration-none text-primary">
                                        <i class="fs-4 bi-people-fill"></i> <span class="ms-1 d-none d-sm-inline">Funcionários</span>
                                    </a>
                                </li>
                            }
                        }
                        else
                        {
                            <li class="nav-item">
                                <a href="/Autenticacao/Login" title="Login" class="nav-link align-middle px-0  text-decoration-none text-primary">
                                    <i class="fs-4 bi-person-check-fill"></i> <span class="ms-1 d-none d-sm-inline">Login</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="/Autenticacao/Registrar" title="Registrar" class="nav-link align-middle px-0  text-decoration-none text-primary">
                                    <i class="fs-4 bi-person-plus-fill"></i> <span class="ms-1 d-none d-sm-inline">Registro</span>
                                </a>
                            </li>
                        }
                    </ul>
                    
                    <hr />
                    
                    @if (User.Identity is not null && User.Identity.IsAuthenticated)
                    {
                        <div class="dropdown pb-4">
                            <a href="/" class="d-flex align-items-center dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="~/img/user.png" alt="Avatar do Usuário" width="30" height="30" class="rounded-circle">
                                <span class="fs-5 d-none d-sm-inline ms-3 text-dark">@User.Identity?.Name</span>
                            </a>
                            <ul class="dropdown-menu text-small shadow">
                                <li>
                                    <form asp-controller="Autenticacao" asp-action="Logout">
                                        <button class="dropdown-item text-dark" type="submit">Logout</button>
                                    </form>
                                </li>
                            </ul>
                        </div>
                    }
                </div>
            </nav>
            <div class="col py-5">
                <main role="main" class="container-sm">
                    <h1 class="fw-semibold">@ViewBag.Title</h1>
                    <hr>
                    <partial name="_Mensagem" model="mensagem"></partial>

                    @RenderBody()
                </main>
            </div>
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LocadoraWebApp/Views/Shared/_Mensagem.cshtml
@model LocadoraWebApp.Models.MensagemViewModel

@if (Model is not null)
{
    var corAlerta = Model.Titulo == "Sucesso" ? "alert-success" : "alert-danger";
    var iconeSelecionado = Model.Titulo == "Sucesso" ? "bi-check-circle-fill" : "bi-info-circle-fill";

    <div class="alert @corAlerta alert-dismissible fade show" role="alert">
        <i class="bi @iconeSelecionado"></i>
        <strong>@Model.Titulo:</strong> @Model.Mensagem
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}