LocadoraWebApp/Controllers/PlanoCobrancasController.cs
using AutoMapper;
using Locadora.Aplicacao.ModuloAutenticacao;
using Locadora.Aplicacao.ModuloGrupoVeiculos;
using Locadora.Aplicacao.ModuloPlanoCobrancas;
using Locadora.Dominio.ModuloPlanoCobrancas;
using LocadoraWebApp.Controllers.Compartilhado;
using LocadoraWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LocadoraWebApp.Controllers
{
    public class PlanoCobrancasController : WebControllerBase
    {
        private readonly ServicoPlanoCobrancas servico;
        private readonly ServicoGrupoVeiculos servicoGrupos;
        private readonly IMapper mapeador;

        public PlanoCobrancasController
        (
            ServicoAutenticacao servicoAutenticacao,
            ServicoPlanoCobrancas servico,
            ServicoGrupoVeiculos servicoGrupos,
            IMapper mapeador
        ) : base(servicoAutenticacao)
        {
            this.servico = servico;
            this.servicoGrupos = servicoGrupos;
            this.mapeador = mapeador;
        }

        public IActionResult Listar()
        {
            var resultado = servico.SelecionarTodos();

            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult());

                return RedirectToAction("Index", "Home");
            }

            var planosCobranca = resultado.Value;

            var listarPlanosVm = mapeador.Map<IEnumerable<ListarPlanoCobrancasViewModel>>(planosCobranca);

            return View(listarPlanosVm);
        }

        public IActionResult Inserir()
        {
            return View(CarregarDadosFormulario());
        }

        [HttpPost]
        public IActionResult Inserir(InserirPlanoCobrancasViewModel inserirVm)
        {
            if (!ModelState.IsValid)
                return View(CarregarDadosFormulario(inserirVm));

            var planoCobrancas = mapeador.Map<PlanoCobrancas>(inserirVm);

            var resultado = servico.Inserir(planoCobrancas);

            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult());

                return RedirectToAction(nameof ( Listar ));
            }

            ApresentarMensagemSucesso($"O registro ID [{planoCobrancas.Id}] foi inserido com sucesso!");

            return RedirectToAction(nameof ( Listar ));
        }

        public IActionResult Editar(int id)
        {
            var resultado = servico.SelecionarPorId(id);

            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult());

                return RedirectToAction(nameof ( Listar ));
            }

            var planoCobranca = resultado.Value;

            var editarVm = mapeador.Map<EditarPlanoCobrancasViewModel>(planoCobranca);

            return View(editarVm);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(EditarPlanoCobrancasViewModel editarVm)
        {
            if (!ModelState.IsValid)
                return View(CarregarDadosFormulario(editarVm));

            var planoCobranca = mapeador.Map<PlanoCobrancas>(editarVm);

            var resultado = servico.Editar(planoCobranca);

            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult());

                return RedirectToAction(nameof ( Listar ));
            }

            ApresentarMensagemSucesso($"O registro ID [{planoCobranca.Id}] foi editado com sucesso!");

            return RedirectToAction(nameof ( Listar ));
        }

        public IActionResult Excluir(int id)
        {
            var resultado = servico.SelecionarPorId(id);

            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult());

                return RedirectToAction(nameof ( Listar ));
            }

            var planoCobranca = resultado.Value;

            var detalhesVm = mapeador.Map<DetalhesPlanoCobrancasViewModel>(planoCobranca);

            return View(detalhesVm);
        }

        [HttpPost]
        public IActionResult Excluir(DetalhesPlanoCobrancasViewModel detalhesVm)
        {
            var resultado = servico.Excluir(detalhesVm.Id);

            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult());

                return RedirectToAction(nameof ( Listar ));
            }

            ApresentarMensagemSucesso($"O registro ID [{detalhesVm.Id}] foi excluído com sucesso!");

            return RedirectToAction(nameof ( Listar ));
        }

        public IActionResult Detalhes(int id)
        {
            var resultado = servico.SelecionarPorId(id);

            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult());

                return RedirectToAction(nameof ( Listar ));
            }

            var planoCobranca = resultado.Value;

            var detalhesVm = mapeador.Map<DetalhesPlanoCobrancasViewModel>(planoCobranca);

            return View(detalhesVm);
        }

        private FormularioPlanoCobrancasViewModel ? CarregarDadosFormulario(FormularioPlanoCobrancasViewModel ? dadosPrevios = null)
        {
            var resultadoGrupos = servicoGrupos.SelecionarTodos();

            if (resultadoGrupos.IsFailed)
            {
                ApresentarMensagemFalha(resultadoGrupos.ToResult());

                return null;
            }

            if (dadosPrevios is null)
                dadosPrevios = new FormularioPlanoCobrancasViewModel();

            dadosPrevios.GruposVeiculos = resultadoGrupos.Value
                .Select(g => new SelectListItem(g.Nome, g.Id.ToString()));

            return dadosPrevios;
        }
    }
}

LocadoraWebApp/Views/PlanoCobrancas/Detalhes.cshtml
@model LocadoraWebApp.Models.DetalhesPlanoCobrancasViewModel

@{
    ViewBag.Title = "Detalhes";
}

<div class="col">
    <partial name="_Informacoes" model="Model"></partial>

    <a asp-action="Listar" class="btn btn-outline-primary px-5 mt-5">
        <i class="bi bi-arrow-return-left me-1"></i>
        Voltar
    </a>
</div>

LocadoraWebApp/Views/PlanoCobrancas/Editar.cshtml
@model LocadoraWebApp.Models.FormularioPlanoCobrancasViewModel

@{
    ViewBag.Title = "Editar plano de cobrança";
}

<div class="col">
    <div class="row gap-3 my-3 my-xl-5">
        <form class="col-lg-6 d-grid gap-3 fs-5" asp-action="Editar">

            <div>
                <label class="control-label fw-semibold mb-1">Grupo de Veículos</label>
                <select class="form-control mb-1" asp-for="GrupoVeiculosId" asp-items="Model.GruposVeiculos"></select>
                <span class="text-danger fs-6" asp-validation-for="GrupoVeiculosId"></span>
            </div>

            <hr>

            <h2 class="text-primary fw-semibold mb-0">Plano Diário</h2>

            <div>
                <label class="control-label fw-semibold mb-1">Preço Diário (Plano Diário)</label>
                <input class="form-control mb-1" asp-for="ValorDiario" type="number" step="0.01" />
                <span class="text-danger fs-6" asp-validation-for="ValorDiario"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Preço por Km (Plano Diário)</label>
                <input class="form-control mb-1" asp-for="ValorKmDiario" type="number" step="0.01" />
                <span class="text-danger fs-6" asp-validation-for="ValorKmDiario"></span>
            </div>

            <hr>

            <h2 class="text-primary fw-semibold mb-0">Plano Controlado</h2>

            <div>
                <label class="control-label fw-semibold mb-1">Quilômetros Disponíveis (Plano Controlado)</label>
                <input class="form-control mb-1" asp-for="QuilometrosDisponiveisPlanoControlado" type="number" step="0.01" />
                <span class="text-danger fs-6" asp-validation-for="QuilometrosDisponiveisPlanoControlado"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Preço Diário (Plano Controlado)</label>
                <input class="form-control mb-1" asp-for="PrecoDiarioPlanoControlado" type="number" step="0.01" />
                <span class="text-danger fs-6" asp-validation-for="PrecoDiarioPlanoControlado"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Preço por Km Extrapolado (Plano Controlado)</label>
                <input class="form-control mb-1" asp-for="PrecoQuilometroExtrapoladoPlanoControlado" type="number" step="0.01" />
                <span class="text-danger fs-6" asp-validation-for="PrecoQuilometroExtrapoladoPlanoControlado"></span>
            </div>

            <hr>

            <h2 class="text-primary fw-semibold mb-0">Plano Livre</h2>

            <div>
                <label class="control-label fw-semibold mb-1">Preço Diário (Plano Livre)</label>
                <input class="form-control mb-1" asp-for="ValorDiarioKmLivre" type="number" step="0.01" />
                <span class="text-danger fs-6" asp-validation-for="ValorDiarioKmLivre"></span>
            </div>

            <div class="d-grid gap-2 d-md-block mt-4">
                <button class="btn btn-primary px-5">
                    <i class="bi bi-floppy-fill me-1"></i>
                    Gravar
                </button>

                <a class="btn btn-outline-primary px-5" asp-action="Listar">
                    <i class="bi bi-arrow-return-left me-1"></i>
                    Voltar
                </a>
            </div>
        </form>
    </div>
</div>

LocadoraWebApp/Views/PlanoCobrancas/Excluir.cshtml
@model LocadoraWebApp.Models.DetalhesPlanoCobrancasViewModel

@{
    ViewBag.Title = "Excluir";
}

<div class="col">
    <partial name="_Informacoes" model="Model"></partial>

    <form class="d-grid gap-2 d-md-block mt-5" asp-action="Excluir">
        <button class="btn btn-danger px-5">
            <i class="bi bi-trash-fill me-1"></i>
            Confirmar
        </button>

        <a class="btn btn-outline-primary px-5" asp-action="Listar">
            <i class="bi bi-arrow-return-left me-1"></i>
            Voltar
        </a>
    </form>
</div>

LocadoraWebApp/Views/PlanoCobrancas/Inserir.cshtml
@model LocadoraWebApp.Models.FormularioPlanoCobrancasViewModel

@{
    ViewBag.Title = "Inserir novo plano de cobrança";
}

<div class="col">
    <div class="row gap-3 my-3 my-xl-5">
        <form class="col-lg-6 d-grid gap-3 fs-5" asp-action="Inserir">

            <div>
                <label class="control-label fw-semibold mb-1">Grupo de Veículos</label>
                <select class="form-control mb-1" asp-for="GrupoVeiculosId" asp-items="Model.GruposVeiculos"></select>
                <span class="text-danger fs-6" asp-validation-for="GrupoVeiculosId"></span>
            </div>

            <hr>

            <h2 class="text-primary fw-semibold mb-0">Plano Diário</h2>

            <div>
                <label class="control-label fw-semibold mb-1">Preço Diário (Plano Diário)</label>
                <input class="form-control mb-1" asp-for="ValorDiario" type="number" step="0.01" />
                <span class="text-danger fs-6" asp-validation-for="ValorDiario"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Preço por Km (Plano Diário)</label>
                <input class="form-control mb-1" asp-for="ValorKmDiario" type="number" step="0.01" />
                <span class="text-danger fs-6" asp-validation-for="ValorKmDiario"></span>
            </div>

            <hr>

            <h2 class="text-primary fw-semibold mb-0">Plano Controlado</h2>

            <div>
                <label class="control-label fw-semibold mb-1">Quilômetros Disponíveis (Plano Controlado)</label>
                <input class="form-control mb-1" asp-for="QuilometrosDisponiveisPlanoControlado" type="number" step="0.01" />
                <span class="text-danger fs-6" asp-validation-for="QuilometrosDisponiveisPlanoControlado"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Preço Diário (Plano Controlado)</label>
                <input class="form-control mb-1" asp-for="PrecoDiarioPlanoControlado" type="number" step="0.01" />
                <span class="text-danger fs-6" asp-validation-for="PrecoDiarioPlanoControlado"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Preço por Km Extrapolado (Plano Controlado)</label>
                <input class="form-control mb-1" asp-for="PrecoQuilometroExtrapoladoPlanoControlado" type="number" step="0.01" />
                <span class="text-danger fs-6" asp-validation-for="PrecoQuilometroExtrapoladoPlanoControlado"></span>
            </div>

            <hr>

            <h2 class="text-primary fw-semibold mb-0">Plano Livre</h2>

            <div>
                <label class="control-label fw-semibold mb-1">Preço Diário (Plano Livre)</label>
                <input class="form-control mb-1" asp-for="ValorDiarioKmLivre" type="number" step="0.01" />
                <span class="text-danger fs-6" asp-validation-for="ValorDiarioKmLivre"></span>
            </div>

            <div class="d-grid gap-2 d-md-block mt-4">
                <button class="btn btn-primary px-5">
                    <i class="bi bi-floppy-fill me-1"></i>
                    Gravar
                </button>

                <a class="btn btn-outline-primary px-5" asp-action="Listar">
                    <i class="bi bi-arrow-return-left me-1"></i>
                    Voltar
                </a>
            </div>
        </form>
    </div>
</div>

LocadoraWebApp/Views/PlanoCobrancas/Listar.cshtml
@model IEnumerable<LocadoraWebApp.Models.ListarPlanoCobrancasViewModel>

    @{
    ViewBag.Title = "Listar planos de cobrança";
    }

<div class="col">

    <a class="btn btn-primary px-4 mt-3" asp-controller="PlanoCobrancas" asp-action="Inserir">
        <i class="bi bi-circle-add"></i>
        Inserir novo plano de cobrança
    </a>

    <div class="row gap-2 my-3 my-xl-5">
        @foreach (var planoVm in Model)
        {
            <div class="card col-lg-5 col-xl-4 px-0">
                <div class="card-header bg-transparent d-flex justify-content-between align-items-center">
                    <h5 class="p-0">@planoVm.Id</h5>

                    <div class="text-end d-flex align-items-center gap-3">
                        <a title="Detalhes"
                           class="text-info-emphasis fs-5"
                           href="/PlanoCobrancas/Detalhes/@planoVm.Id">
                            <i class="bi bi-search"></i>
                        </a>
                        <a title="Editar"
                           class="text-info-emphasis fs-5"
                           href="/PlanoCobrancas/Editar/@planoVm.Id">
                            <i class="bi bi-pencil-fill"></i>
                        </a>
                        <a title="Excluir"
                           class="text-info-emphasis fs-5" href="/PlanoCobrancas/Excluir/@planoVm.Id">
                            <i class="bi bi-trash-fill"></i>
                        </a>
                    </div>
                </div>

                <div class="card-body">
                    <h5 class="card-title">Grupo de Veículos: @planoVm.GrupoVeiculos</h5>
                    <p class="card-text">
                        Preço Diário (Diário): @planoVm.PrecoDiarioPlanoDiario.ToString() <br />
                        Preço por Km (Diário): @planoVm.PrecoQuilometroPlanoDiario.ToString() <br />
                        Km Disponíveis (Controlado): @planoVm.QuilometrosDisponiveisPlanoControlado Km(s)<br />
                        Preço Diário (Controlado): @planoVm.PrecoDiarioPlanoControlado.ToString() <br />
                        Preço por Km Extrapolado (Controlado): @planoVm.PrecoQuilometroExtrapoladoPlanoControlado.ToString() <br />
                        Preço Diário (Livre): @planoVm.PrecoDiarioPlanoLivre.ToString()
                    </p>
                </div>
            </div>
        }
    </div>
</div>

LocadoraWebApp/Views/PlanoCobrancas/_Informacoes.cshtml
@model LocadoraWebApp.Models.DetalhesPlanoCobrancasViewModel

<div class="row gap-3 my-3 my-xl-5">
    <label class="fs-4"><strong>Grupo de Veículos:</strong> @Model.GrupoVeiculos</label>

    <label class="fs-4"><strong>Preço Diário (Plano Diário):</strong> @Model.PrecoDiarioPlanoDiario.ToString("C2")</label>

    <label class="fs-4"><strong>Preço por Km (Plano Diário):</strong> @Model.PrecoQuilometroPlanoDiario.ToString("C2")</label>

    <label class="fs-4"><strong>Km Disponíveis (Plano Controlado):</strong> @Model.QuilometrosDisponiveisPlanoControlado km(s)</label>

    <label class="fs-4"><strong>Preço Diário Controlado (Plano Controlado):</strong> @Model.PrecoDiarioPlanoControlado.ToString("C2")</label>

    <label class="fs-4"><strong>Preço por Km extrapolado (Plano Controlado):</strong> @Model.PrecoQuilometroExtrapoladoPlanoControlado.ToString("C2")</label>

    <label class="fs-4"><strong>Preço Livre (Plano Livre):</strong> @Model.PrecoDiarioPlanoLivre.ToString("C2")</label>

    <label class="fs-5"><strong>Id:</strong> [@Model.Id]</label>
</div>